# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Thingy', max_length=35),
            preserve_default=False,
        ),
    ]
