# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160418_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.AddField(
            model_name='condition',
            name='cond_grade',
            field=models.IntegerField(default=0),
        ),
    ]
