# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=b'postimages/default.png', upload_to=b'postimages/'),
        ),
    ]
