# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160511_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_rating',
            name='postID',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='reviewauthor',
        ),
        migrations.DeleteModel(
            name='Post_rating',
        ),
        migrations.DeleteModel(
            name='PostReview',
        ),
    ]
