# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160511_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
