# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160420_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='postID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postreview',
            old_name='postID',
            new_name='post',
        ),
    ]
