# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160520_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
