# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160526_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area_code',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
