# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
