# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160420_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
