# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160422_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Condition'),
        ),
    ]
