# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20160425_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
