# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160425_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=b'Images/None-No-img.jpg', upload_to=b'Images/'),
        ),
    ]
