# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=b'postimages/None-No-img.jpg', upload_to=b'postimages/'),
        ),
    ]
