# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20160527_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, max_length=2000)),
                ('unread', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentMessage',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.BaseMessage')),
                ('type', models.CharField(choices=[(b'Rent request', b'Rent request'), (b'Rent accepted', b'Rent accepted'), (b'Rent declined', b'Rent declined')], default='Rent request', max_length=13)),
                ('unread', models.BooleanField(default=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('message.basemessage',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.BaseMessage')),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Accepted', b'Accepted'), (b'Declined', b'Declined'), (b'Ended', b'Ended')], default='Pending', max_length=8)),
            ],
            bases=('message.basemessage',),
        ),
        migrations.AddField(
            model_name='basemessage',
            name='rentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_rentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemessage',
            name='thingy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
