# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20160511_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RentMessage',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.BaseMessage')),
                ('type', models.CharField(choices=[(b'Rent', b'Rent request'), (b'Acc', b'Rent accepted'), (b'Dec', b'Rent declined')], default='Rent', max_length=4)),
            ],
            bases=('message.basemessage',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='message.BaseMessage')),
                ('status', models.CharField(choices=[(b'Pen', b'Pending'), (b'Acc', b'Accepted'), (b'Dec', b'Declined')], default='Pen', max_length=3)),
            ],
            bases=('message.basemessage',),
        ),
        migrations.AddField(
            model_name='basemessage',
            name='rentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemessage',
            name='thingy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
