# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemessage',
            name='thingy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_thingy', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='rentmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
