# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentmessage',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
