# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rentmessage_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemessage',
            old_name='thingy_id',
            new_name='thingy',
        ),
    ]
