# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20160518_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
