# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20160512_0849'),
        ('message', '0003_auto_20160512_0834'),
    ]

    operations = [
    ]
