# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20160530_1107'),
        ('message', '0009_auto_20160526_1224'),
    ]

    operations = [
    ]
