# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160511_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='revieweduser',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
