# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default=b'userimages/None-No-img.jpg', upload_to=b'userimages/'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(default=b'userimages/None-No-img.jpg', upload_to=b'userimages'),
        ),
    ]
