# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160427_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default=b'userimages/default.png', upload_to=b'userimages/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tagline',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
