# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default=b'userimages/None-No-img.jpg', upload_to=b'userimages/'),
        ),
    ]
