# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20160502_0752'),
        ('authentication', '0006_auto_20160502_0742'),
    ]

    operations = [
    ]
